[package]
name = "miditran"
version = "0.3.5"
edition = "2018"
authors = ["Sean Cross <sean@xobs.io>"]
license = "Apache-2.0"

[dependencies]
clap = "2.33.1"
midir = "0.7.0"
enigo = "0.0.14"

[features]

debug = []
